/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kakuro.forms;
import java.awt.Dimension;/*
import java.awt.FlowLayout;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;*/
import java.awt.GridLayout;
import javax.swing.JButton;

/**
 *
 * @author Anthony
 */
public class Principal extends javax.swing.JFrame {
    
    final int[][] logicalMatrix;
    JButton[][] physicalMatrix;
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        logicalMatrix = new int[14][14];
        physicalMatrix = new JButton[14][14];
        
        generarBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCreacion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCrearKakuro = new javax.swing.JButton();
        cboCrear = new javax.swing.JComboBox<>();
        panelResolver = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnResolver = new javax.swing.JButton();
        comboResolver = new javax.swing.JComboBox<>();
        panelMatriz = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 710));
        setMinimumSize(new java.awt.Dimension(900, 710));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Crear Kakuro");

        btnCrearKakuro.setText("Crear");
        btnCrearKakuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearKakuroActionPerformed(evt);
            }
        });

        cboCrear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Con Hilos", "Con Procesos" }));
        cboCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCreacionLayout = new javax.swing.GroupLayout(panelCreacion);
        panelCreacion.setLayout(panelCreacionLayout);
        panelCreacionLayout.setHorizontalGroup(
            panelCreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(panelCreacionLayout.createSequentialGroup()
                        .addComponent(cboCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCrearKakuro)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCreacionLayout.setVerticalGroup(
            panelCreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearKakuro))
                .addGap(42, 42, 42))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Resolver Kakuro");

        btnResolver.setText("Resolver");
        btnResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResolverActionPerformed(evt);
            }
        });

        comboResolver.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Con Hilos", "Con Procesos" }));

        javax.swing.GroupLayout panelResolverLayout = new javax.swing.GroupLayout(panelResolver);
        panelResolver.setLayout(panelResolverLayout);
        panelResolverLayout.setHorizontalGroup(
            panelResolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResolverLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelResolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelResolverLayout.createSequentialGroup()
                        .addComponent(comboResolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnResolver))
                    .addGroup(panelResolverLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelResolverLayout.setVerticalGroup(
            panelResolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResolverLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(panelResolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResolver)
                    .addComponent(comboResolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout panelMatrizLayout = new javax.swing.GroupLayout(panelMatriz);
        panelMatriz.setLayout(panelMatrizLayout);
        panelMatrizLayout.setHorizontalGroup(
            panelMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        panelMatrizLayout.setVerticalGroup(
            panelMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelResolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCreacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelMatriz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panelCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelResolver, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResolverActionPerformed
        // TODO add your handling code here:
        prueba("3");
    }//GEN-LAST:event_btnResolverActionPerformed

    private void cboCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCrearActionPerformed

    private void btnCrearKakuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearKakuroActionPerformed
        // TODO add your handling code here:
        prueba("4");
    }//GEN-LAST:event_btnCrearKakuroActionPerformed
    
    final void generarBotones(){
        
        panelMatriz.setLayout(new GridLayout(14,14));
        
        panelMatriz.setPreferredSize(new Dimension(620,679));
        
        for (JButton[] physicalMatrix1 : physicalMatrix) {
            for (int j = 0; j < physicalMatrix1.length; j++) {
                physicalMatrix1[j] = new JButton(); //String.valueOf(i)+"↓"+String.valueOf(j)+"→");
                physicalMatrix1[j].setVisible(true);
                physicalMatrix1[j].setEnabled(false);
                physicalMatrix1[j].setPreferredSize(new Dimension(50,50));
                panelMatriz.add(physicalMatrix1[j]);
            }
        }
        /* MI VERSION DE CODIGO QUE FUNCIONA
        for(int i = 0; i<physicalMatrix.length;i++){
            for(int j = 0; j<physicalMatrix[i].length;j++){
                
                physicalMatrix[i][j] = new JButton();//String.valueOf(i)+"↓"+String.valueOf(j)+"→");
                physicalMatrix[i][j].setVisible(true);
                physicalMatrix[i][j].setEnabled(false);
                physicalMatrix[i][j].setPreferredSize(new Dimension(50,50));
                panelMatriz.add(physicalMatrix[i][j]);
                
                
            }
        }
        */
        getContentPane().add(panelMatriz);
        pack();
        setVisible(true);
        
    }
    
    
    void prueba(String valor){
        for (JButton[] physicalMatrix1 : physicalMatrix) {
            for (JButton physicalMatrix11 : physicalMatrix1) {
                physicalMatrix11.setText(valor);
            }
        }
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearKakuro;
    private javax.swing.JButton btnResolver;
    private javax.swing.JComboBox<String> cboCrear;
    private javax.swing.JComboBox<String> comboResolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelCreacion;
    private javax.swing.JPanel panelMatriz;
    private javax.swing.JPanel panelResolver;
    // End of variables declaration//GEN-END:variables
}
